---

# If you’re running Ubuntu 16.04 LTS (Xenial Xerus) or later, including Ubuntu 18.04 LTS (Bionic Beaver), 
# Ubuntu 18.10 (Cosmic Cuttlefish) and Ubuntu 19.10 (Eoan Ermine), you don’t need to do anything. 
# Snap is already installed and ready to go.

- name: Ensure snapd is enabled.
  systemd:
    name: snapd.socket
    enabled: true

- name: Update snap after install.
  shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false

- name: Install certbot via snap.
  shell: "snap install --classic certbot"

- name: Symlink certbot into place.
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Set Certbot script variable.
  set_fact:
    certbot_script: /usr/bin/certbot
